### ISSUE TITLE
Stopped registering pushToken on Braze after mParticle upgrade to version 5.42.2.

### ISSUE THREAD

**Issue by sky-matheusalves** [mparticle-integrations/mparticle-android-integration-appboy#106]
When upgraded to version v5.42.2, braze version was also incremented from v21.0.0 to v23.2.0.
Here is the PR:
https://github.com/mParticle-integrations/mparticle-android-integration-appboy/compare/b7d610157f7e6675ab20867c994fa74ff6987edd...425cd9870ffb13f29e03981d0e3698543a59b9bf#

At Braze version 22.0.0 a big refactor was done, changing java code to kotlin.
https://www.braze.com/docs/developer_guide/platform_integration_guides/android/changelog#2300

The problem is, there is a missing set attribute at `Class AppboyKit` line 439 and  523.
Please change this line
`Braze.getInstance(context).registeredPushToken`
to this one
`Braze.getInstance(context).registeredPushToken = instanceId`

Wish you the best,
Matheus Correa.

**Comment by mchuangatmp** [comment]
@sky-matheusalves Thanks for letting us know, we will take a look.  In the future, if you already have the fix...feel free to open a PR and we'll review it right away

**Comment by mchuangatmp** [comment]
@sky-matheusalves we released the change you suggested in v5.48.3, i'm going to close this ticket now.  Please contact support if you have further issues.
