### ISSUE TITLE
Braze/Appboy integration out of date

### ISSUE THREAD

**Issue by mateot1** [mparticle-integrations/mparticle-android-integration-appboy#45]
The primary breaking change that needs to be addressed is that `AppboyFcmReceiver` no longer exists. Braze docs say to replace with `AppboyFirebaseMessagingService` or use `AppboyFirebaseMessagingService.handleBrazeRemoteMessage` if you have your own extension of `FirebaseMessagingService`. The latter is what applied to our app and seems to work, but I am not sure if it bypasses any events mparticle is sending for displaying notifications.

**Comment by alexs-mparticle** [comment]
@mateot1 Just chiming in here to let you know that I responded to your recent message in the attached repo: https://github.com/mParticle/mparticle-android-sdk/issues/63

**Comment by alexs-mparticle** [comment]
Closing this issue as the attached thread has been closed.
