### ISSUE TITLE
Readme is out of date

### ISSUE THREAD

**Issue by mateot1** [mparticle-integrations/mparticle-android-integration-appboy#56]
FYI, looks like braze/appboy renamed more things in v15 and added the preferred naming of `braze` for their xml config in v16: https://www.braze.com/docs/developer_guide/platform_integration_guides/android/changelog/#1500 

The readme still references `AppboyFcmReceiver` and uses the old package as well for the `BrazePushReceiver` manifest example. Also the `appboy` xml example should probably use `braze` now.

**Comment by willpassidomo** [comment]
Hey @mateot1 , thanks for bringing this up, it looks like I missed those in the last update! Just merged in the PR, let me know if we missed anything in there
