### ISSUE TITLE
Not passing instance ID to the Braze SDK after login

### ISSUE THREAD

**Issue by samuelcai-chancetop** [mparticle-integrations/mparticle-android-integration-appboy#79]
In AppboyKit.java, I only see `Braze.getInstance(getContext()).registerAppboyPushMessages(instanceId);` in `onPushRegistration`, don't see it in `onLoginCompleted`.

So this causes an issue:
Install and open app, the instanceId is associated with an anonymous user. Now login, but user can't receive push notification, because the instanceId is still associate with the anonymous one.

To fix this, I'm thinking this:
save the instanceId got from `onPushRegistration`, and registerAppboyPushMessages again in `onLoginCompleted` and `onLogoutCompleted`

**Comment by mchuangatmp** [comment]
@samuelcai-chancetop thanks for feedback...while converting this kit to Kotlin, we added `registerAppboyPushMessages(instanceId)` to `onUserIdentified` in our latest version (5.44.0).  

Tracked internally as SQDSDKS-4314
