### ISSUE TITLE
No method mapped to Braze's removeFromCustomAttributeArray

### ISSUE THREAD

**Issue by dwillislc** [mparticle-integrations/mparticle-android-integration-appboy#8]
Hello, 

David here from Braze and a mutual client of ours has found that the current Braze Kit for your Android SDK does not support Braze's `[appboyUser.removeFromCustomAttributeArray("custom_attribute_array_test", testRemString);](https://www.braze.com/documentation/Android/#setting-a-custom-attribute-with-an-array-value
)` method. 

You can see in the mapping file that your [`removeUserAttribute`](https://github.com/mParticle/mparticle-android-sdk/blob/master/android-core/src/main/java/com/mparticle/identity/MParticleUser.java#L151) only supports the [`unsetCustomUserAttribute`](https://github.com/mparticle-integrations/mparticle-android-integration-appboy/blob/master/src/main/java/com/mparticle/kits/AppboyKit.java#L259
) method. 

On your iOS SDK, we see that the [method](https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/blob/master/mParticle-Appboy/MPKitAppboy.m#L126) is supported. 

Looking at your `removeUserAttribute` method we're unsure if adding the method would fit into your existing API, but would very much appreciate parity across the Android and iOS Braze Kits. 

@Bucimis

**Comment by samdozor** [comment]
@Bucimis before implementing this I had a couple questions - can you have custom user attributes with the same key, that are both arrays and non-array? The reason I ask is that mParticle enforces that they are unique, which is why we only have a single remove API. To support this for Braze we might need to determine if the given key is an array or not such that we call the correct Braze API.

**Comment by Bucimis** [comment]
@samdozor custom attribute keys are unique in Braze as well. `removeFromCustomAttributeArray` allows you to remove specific values from the array (as opposed to removing the entire key-value pair)

**Comment by willpassidomo** [comment]
closing this out as part of cleanup, issue was fixed earlier this year :)
